# Site settings
title: Whitemir
SEOTitle: Whitemir's blog
description: I wanna sleep.
keyword: "Coding until the day I become a Rolls-Royce owner"
url: "http://127.0.0.1:4000"      # your host, for absolute URL
baseurl: ""                                         # for example, '/blog' if your blog hosted on 'host/blog'
avatar: "img/whitemir.png"                    # the avatar showing on the homepage


# GitHub repository (if the site is hosted by GitHub)
repository: ColdBurgundy
repository_branch: main


# Theme style settings
theme_style:
  highlight:    # "dark" (default), "light"
  alert:        # "flat" (default), "modern"
  post_preview: # "image" (default), "text"
                # display post's featured image on homepage or not


# Markdown enhancements settings
math:
  enable: true    # false (default), true
                  # math rendering for all posts and keynotes
  engine:         # "katex" (default), "mathjax"
                  # only make sense when `math.engine: true`
chart: true       # false (default), true
mermaid: true     # false (default), true
emoji-plus: true  # false (default), true


# CDN settings
cdn:
  source:       # "jsdelivr" (default), "bootcdn", "unpkg", "cdnjs"
  enable:       # false (default), true
                # optimizing asset files via jsDelivr or not


# Publish posts or collection documents with a future date.
future: true

collections:
  experiences:
    output: true
  publications:
    output: true
  projects:
    output: true


# SNS settings
sns:
  RSS: true
  github_username: Coldburgundy
  linkedin_username: 
  email_address: renovamenzxh@gmail.com


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - package.json
  - package-lock.json
  - README.md
  - README-CN.md
  - LICENSE
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
  - /node_modules
anchorjs: true  # if you want to customize anchor. check out `anchor.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN


# Gems
# you have to `bundle config set path 'vendor/bundle' && bundle install` before local preview
plugins:
  - jekyll-paginate
  - jemoji


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    disable: true                  # we use highlight.js for syntax highlighting, so we disable rouge here


# Navigation menu settings
menus:
  - title: Home
    font: fab fa-fort-awesome
    url: /
  - title: About
    font: fas fa-user-astronaut
    url: /about/
  - title: Untitled 『Writing』
    font: fas fa-paw
    submenus:
      - title: Advice to me
        font: fas fa-user-astronaut    
        url: /Advice-to-me
        icon: "think.png"
      - title: Miscellaneous thoughts
        font: fas fa-user-astronaut    
        url: /Miscellaneous-thoughts
        icon: "idea.png"
  - title: Untitled 『Studying CS』
    font: fas fa-paw
    submenus:
      - title: Data Structure
        font: fas fa-user-astronaut
        url: /#
      - title: ------------------------------
        font: fas fa-user-astronaut      
        url: /$
      - title: Algorithms
        font: fas fa-user-astronaut
        url: /#
      - title: CLRS
        font: fas fa-user-astronaut
        url: /CLRS/
        icon: "algorithm.png"
      - title: BOJ(acmicpc.net)
        font: fas fa-user-astronaut
        url: /BOJ/ 
        icon: "boj.png"
      - title: ------------------------------
        font: fas fa-user-astronaut
        url: /$           
      - title: Computer Architecture
        font: fas fa-user-astronaut
        url: /#
      - title: CSAPP
        font: fas fa-user-astronaut
        url: /CSAPP/
        icon: "book.png"
      - title: ------------------------------
        font: fas fa-user-astronaut
        url: /$
      - title: Operating System
        font: fas fa-user-astronaut
        url: /#
      - title: Operating System Concepts 10e
        font: fas fa-user-astronaut
        url: /Operating-System-Concepts-10e/
      - title: 64비트 멀티코어 OS 원리와 구조 1
        font: fas fa-user-astronaut
        url: /64비트-멀티코어-OS-원리와-구조-1/
        icon: "book.png"
      - title: 64비트 멀티코어 OS 원리와 구조 2
        font: fas fa-user-astronaut
        url: /64비트-멀티코어-OS-원리와-구조-2/  
        icon: "book.png"
      - title: ------------------------------
        font: fas fa-user-astronaut
        url: /$                            
      - title: Network
        font: fas fa-user-astronaut
        url: /#
      - title: ------------------------------
        font: fas fa-user-astronaut
        url: /$       
      - title: Database
        font: fas fa-user-astronaut
        url: /#                                          
  - title: Projects
    font: fas fa-book
    url: /projects/
  - title: Archive
    font: fas fa-archive
    url: /archive/

# Comment settings
comment:
  provider: gitalk # false (default), "disqus", "gitalk", "valine"

  # Disqus settings
  disqus_username: renovamen

  # Gitalk settings
  # https://github.com/gitalk/gitalk
  gitalk:
    clientID: 'faf464da633b08ff5317'
    clientSecret: '402324fc860894e5fcba6320fddbddd1ec7f5644'
    repo: gitalk-comments
    owner: This-is-an-Apple
    admin:
      - Renovamen
      - This-is-an-Apple

  # Valine settings
  # https://valine.js.org/
  valine:
    appID:
    appKey:


# Analytics settings
analytics:
  # Baidu Analytics
  ba_track_id: 00504d7a0bf51278aa92b36e60e830b5 # [your baidu track id]

  # Google Analytics
  ga_track_id: 'G-ZYM02DSEHS'               # [your google track id]


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Whether or not to enable Hitokoto (the bubble on homepage)
hitokoto: true # default: false
